all: selectionSort.c insertionSort.c ../utilities.h
	gcc selectionSort.c -o selectionSort
	gcc insertionSort.c -o insertionSort


selectionSort: ../utilities.h
	gcc selectionSort.c -o selectionSort

insertionSort: ../utilities.h
	gcc insertionSort.c -o insertionSort