all: selectionSort insertionSort bubbleSort


selectionSort: ../utilities.h
	gcc selectionSort.c -o selectionSort

insertionSort: ../utilities.h
	gcc insertionSort.c -o insertionSort

bubbleSort: ../utilities.h
	gcc bubbleSort.c -o bubbleSort
